name: Release

on:
  push:
    tags:
      - 'v*'  # Triggered when a tag is pushed

jobs:
  publish:
    name: Publish Go Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
          
      - name: Verify Module
        run: |
          go mod verify
          
      - name: Notify Go Module Index
        run: |
          # Attendre que le tag soit complètement propagé
          sleep 30
          curl -X GET "https://proxy.golang.org/github.com/${{ github.repository }}/@v/${{ github.ref_name }}.info"
